### ISSUE TITLE
Great resource

### ISSUE THREAD

**Issue by dominikwilkowski** [fabiantheblind/extendscript#5]
Thanks for the work.

I am actually trying to find a way to delete empty groups in the swatches panel:
![screen shot 2016-06-22 at 3 53 03 pm](https://cloud.githubusercontent.com/assets/1266923/16255918/6bb9117c-3891-11e6-9186-1047eaaba920.png)

I can't seem to find a way to even read them other then going through swatches and reading `parentColorGroup`. Any hint is appreciated.

Cheers

**Comment by fabiantheblind** [comment]
Hi @dominikwilkowski great you like it. We moved the wiki to a new home. https://github.com/extendscript/wiki/wiki 

This snippet shows how to remove empty `colorGroups`.

```js
var doc = app.activeDocument; // get the doc
var grp1 = doc.colorGroups.add('empty group'); // add a new group
var grp2 = doc.colorGroups.add('not empty group'); // add another
var col = doc.colors.add(); // create a color
grp2.colorGroupSwatches.add(col); // move the color to a group

// loop all groups and remove the empty ones
for (var i = doc.colorGroups.length - 1; i >= 0; i--) {
  if (doc.colorGroups[i].colorGroupSwatches.length === 0) {
    $.writeln('group "' + doc.colorGroups[i].name + '" is empty. removing it!');
    doc.colorGroups[i].remove();
  } else {
    $.writeln('this group is not empty');
  }
}
```

Are you writing a lot of ExtendScript? If so would you like to join the ExtendScript Org? No strings attached. We are trying to round up more people that write extendscript.

**Comment by dominikwilkowski** [comment]
Hey @fabiantheblind 
Thanks for the swift reply. I will be trying you script tomorrow in our project and get back to you.

We are just starting to build integrations into our [Design System GUI](https://gel.westpacgroup.com.au/GUI/WBC/) and got already some stuff done. Would love to join and see if I can add value. The docs from Adobe are awful at best ;)
Let me know what you are looking for. Is there a slack channel? Should there be?

**Comment by fabiantheblind** [comment]
You have an invite under https://github.com/ExtendScript and Yes the docs are pretty old. Take a look at https://github.com/ExtendScript/organisation-rules as well. Also ExtendScript is pretty old. We are just looking for getting some people together. Maybe we can have some impact on Adobe to update their scripting engine to something that is up to date. If you want to contribute the wiki is a good place to start or the Orgs website. @wridgers started working on it but more hands can get it done faster.

**Comment by dominikwilkowski** [comment]
Works like a charm. Thanks for that. We have some contacts to Adobe (being a large company and all) and have been asked by them what we think should improve. Let me see if I can tie up a contact there we can talk to about extendScript. The thing I am missing most is ES8 or 7 for that matter. But that's just me ;)

**Comment by fabiantheblind** [comment]
This would be amazing. Having es6 or even 7 or 8 features would push things forward
